# KIdney dataset

Here we are creating dataset for kidney dataset

In [1]:
import os
from pathlib import Path

current_path = Path.cwd().resolve()
repository_root = next(
    path
    for path in (current_path, *current_path.parents)
    if (path / "pyproject.toml").is_file()
)
os.chdir(repository_root)

repository_root

PosixPath('/home/max/repositories/MSIAutoEncoderWrapper')

In [2]:
# load dataset
from IPython.display import display

from msi_autoencoder_wrapper.dataset_management.exploration import DatasetExplorer

# REMARK: date i download DB is  12.08.2026 (DD, MM, YYYY) 
explorer = DatasetExplorer(
    source="metaspace",
    # Save the METASPACE dataset catalogue in this directory.
    cache_dir="assets/local/datasets/metaspace",
    # Set to True to request the catalogue again and replace the local file.
    refresh_cache=False,
)

# The same interface can be initialized for PRIDE:
# pride_explorer = DatasetExplorer(source="pride")

2026-08-12 13:15:37,427 | INFO     | msi_autoencoder_wrapper.utils.module_search:79 | Discovered 5 implementation module(s) in package 'msi_autoencoder_wrapper.dataset_management.sources.strategies'.
2026-08-12 13:15:38,787 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.metaspace:291 | Loaded 19783 METASPACE catalogue records from assets/local/datasets/metaspace/available-datasets.json

# About kidney

I choosed kidney as it is most countable dataset

In [3]:
# Replace the key with another enumerable entry from `available_filters`.
organism_values = explorer.get_available_values("organism_part")
display(organism_values.head(30))

# Typical additional inspections:
# display(explorer.get_available_values("organism_part").head(30))
# display(explorer.get_available_values("polarity"))
# display(explorer.get_available_values("analyzer_type").head(30))
# display(explorer.get_available_values("ionisation_source").head(30))
# display(explorer.get_|available_values("maldi_matrix").head(30))

,value,label,count,variants
0,Kidney,Kidney,4436,"Kidney (4078), kidney (342), Kidney (14), kid..."
1,Brain,Brain,2143,"Brain (2108), brain (35)"
2,Cell Line,Cell Line,971,Cell Line (971)
3,Liver,Liver,945,"Liver (887), liver (51), LIVER (7)"
4,Root,Root,870,"Root (457), root (413)"
5,Lung,Lung,809,"Lung (700), lung (109)"
6,Whole organism,Whole organism,809,"Whole organism (774), whole organism (35)"
7,leaf,leaf,784,"leaf (622), Leaf (162)"
8,Breast,Breast,514,Breast (514)
9,N/A,N/A,425,"N/A (423), n/a (2)"
10,Kidney Cortex,Kidney Cortex,387,"Kidney Cortex (386), Kidney cortex (1)"
11,Skin,Skin,364,"Skin (332), SKin (24), skin (8)"
12,Ovary,Ovary,297,"Ovary (290), ovary (7)"
13,Lymph node,Lymph node,267,Lymph node (267)
14,Stem,Stem,253,"Stem (241), stem (12)"
15,Colon,Colon,237,"Colon (181), colon (56)"
16,Seed,Seed,220,"Seed (121), seed (99)"
17,Cells,Cells,213,"Cells (212), cells (1)"
18,None,None,194,"None (181), none (13)"
19,Heart,Heart,175,"Heart (159), heart (13), Heart (3)"
20,Gill,Gill,149,"Gill (121), gill (28)"
21,rhizosphere,rhizosphere,142,rhizosphere (142)
22,Wood_fungal,Wood_fungal,127,Wood_fungal (127)
23,standards,standards,124,standards (124)
24,Microbial colony,Microbial colony,121,Microbial colony (121)
25,Epididymis,Epididymis,115,Epididymis (115)
26,Spot,Spot,115,Spot (115)
27,Fibroblasts,Fibroblasts,103,Fibroblasts (103)
28,Root exudates,Root exudates,84,"Root exudates (74), Root Exudates (10)"
29,Pancreas,Pancreas,79,"Pancreas (78), pancreas (1)"

In [4]:
broad_filters = {
    # Biological metadata
    "organism": "Mouse",
    "organism_part": "kidney",
    "condition": "Wildtype",

    # Acquisition metadata
    "polarity": "Negative",
    # "ionisation_source": "MALDI", - we can normalize this later 

    # Annotation filters
    # "status": "FINISHED",
    "annotation_fdr": 0.1,
    # "has_optical_image": True,
    "min_annotation_count": 1,

}

results = explorer.filter(broad_filters)

display(results)
print(f"Found {len(results)} datasets")

2026-08-12 13:15:42,068 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.metaspace:550 | METASPACE cache reduced discovery to 61 candidate datasets

METASPACE discovery:   0%|          | 0/3 [00:00<?, ?stage/s]

Current operation:   0%|          | 0/1 [00:00<?, ?operation/s]

2026-08-12 13:15:43,151 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.metaspace:267 | METASPACE discovery accepted 60 datasets and rejected 8708 datasets
2026-08-12 13:15:43,153 | INFO     | msi_autoencoder_wrapper.dataset_management.exploration.dataset_explorer:123 | Explorer retained 60 records from source metaspace

,dataset_id,name,source,project_accession,project_url,organisms,organism_parts,condition,growth_conditions,diseases,...,unannotated_pixel_count,annotated_pixel_fraction,annotation_fdr,spatial_annotation_count,spatial_annotation_database_count,spatial_stats_status,molecule_count,unique_molecule_count,unique_molecules,excluded
0,2026-04-22_21h03m00s,kidney_test_metabolites_null_mz_shift_10_til_550,metaspace,None,https://metaspace2020.eu/dataset/2026-04-22_21...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
1,2025-04-14_15h53m53s,00070_lgruber_qcl-msi_data11_glomeruli_wt_rms,metaspace,None,https://metaspace2020.eu/dataset/2025-04-14_15...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
2,2025-04-14_09h06m15s,00070_lgruber_qcl-msi_het-0717_data3_slide1-rms,metaspace,None,https://metaspace2020.eu/dataset/2025-04-14_09...,Mus musculus (mouse),Kidney,Wild type,,,...,None,None,0.1,None,None,None,None,None,,False
3,2025-04-14_09h00m43s,00070_lgruber_qcl-msi_het-0707_data5_slide1-rms,metaspace,None,https://metaspace2020.eu/dataset/2025-04-14_09...,Mus musculus (mouse),Kidney,Wild type,,,...,None,None,0.1,None,None,None,None,None,,False
4,2025-04-14_15h55m50s,00070_lgruber_qcl-msi_timson_glomeruli_data2_w...,metaspace,None,https://metaspace2020.eu/dataset/2025-04-14_15...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
5,2025-04-14_09h56m19s,00070_lgruber_qcl-msi_wt-4625_data6_slide1-rms,metaspace,None,https://metaspace2020.eu/dataset/2025-04-14_09...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
6,2025-04-14_10h18m43s,00070_lgruber_qcl-msi_wt-4628_data1_slide1-rms,metaspace,None,https://metaspace2020.eu/dataset/2025-04-14_10...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
7,2025-07-07_13h56m06s,mo6_metabolites,metaspace,None,https://metaspace2020.eu/dataset/2025-07-07_13...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
8,2025-07-07_13h03m27s,msi2024013_20240909_multiomicsiii_nor_300-1350...,metaspace,None,https://metaspace2020.eu/dataset/2025-07-07_13...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
9,2025-07-07_10h55m54s,msi2024013_20240909_multiomicsii_nedc 50-650_f...,metaspace,None,https://metaspace2020.eu/dataset/2025-07-07_10...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
10,2025-07-06_22h07m04s,msi2024013_20240909_multiomicsii_nor 50-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_22...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
11,2025-07-06_19h01m02s,msi2024013_20240909_multiomicsii_nedc 300-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_19...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
12,2025-07-06_16h31m32s,msi2024013_20240909_multiomicsii_nedc 50-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_16...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
13,2025-07-06_15h14m05s,msi2024013_20240909_multiomicsii_nedc 50-650,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_15...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
14,2025-06-26_11h11m17s,kidney_nedc_1-3mg_recryst_m2,metaspace,None,https://metaspace2020.eu/dataset/2025-06-26_11...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
15,2025-06-26_10h27m59s,kidney_nedc_1-3mg_recryst_m1,metaspace,None,https://metaspace2020.eu/dataset/2025-06-26_10...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
16,2025-06-26_10h05m06s,kidney_nedc_0-5mg_recryst_m2,metaspace,None,https://metaspace2020.eu/dataset/2025-06-26_10...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
17,2025-06-26_09h26m30s,kidney_nedc_0-5mg_recryst_m1,metaspace,None,https://metaspace2020.eu/dataset/2025-06-26_09...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
18,2025-06-25_16h01m21s,Kidney_NEDC_M2_Thresholded,metaspace,None,https://metaspace2020.eu/dataset/2025-06-25_16...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
19,2025-06-24_15h36m14s,Kidney_NEDC_1-3mg_MALDI-2,metaspace,None,https://metaspace2020.eu/dataset/2025-06-24_15...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
20,2025-06-24_17h32m20s,2025-06-24_kidney_neg_thin_m2,metaspace,None,https://metaspace2020.eu/dataset/2025-06-24_17...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
21,2025-06-24_17h05m47s,Kidney_NEDC_0-5mg_MALDI-2,metaspace,None,https://metaspace2020.eu/dataset/2025-06-24_17...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
22,2025-06-24_16h31m14s,Kidney_NEDC_0-5mg,metaspace,None,https://metaspace2020.eu/dataset/2025-06-24_16...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
23,2025-06-24_16h02m08s,2025-06-24_kidney_neg_thin,metaspace,None,https://metaspace2020.eu/dataset/2025-06-24_16...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
24,2025-06-24_14h51m14s,Kidney_NEDC_1-3mg,metaspace,None,https://metaspace2020.eu/dataset/2025-06-24_14...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
25,2024-06-12_15h33m53s,NEDC_imaging_kidney_K10_replicate3,metaspace,None,https://metaspace2020.eu/dataset/2024-06-12_15...,mouse,Kidney,Wild type,,,...,None,None,0.1,None,None,None,None,None,,False
26,2024-06-12_15h32m57s,NEDC_imaging_kidney_K8_replicate2,metaspace,None,https://metaspace2020.eu/dataset/2024-06-12_15...,mouse,kidney,Wild type,,,...,None,None,0.1,None,None,None,None,None,,False
27,2024-06-12_15h27m25s,NEDC_imaging_kidney_K6_replicate1,metaspace,None,https://metaspace2020.eu/dataset/2024-06-12_15...,mouse,Kidney,Wild type,,,...,None,None,0.1,None,None,None,None,None,,False
28,2024-05-23_14h25m01s,K3 vs K6 neg -Jano,metaspace,None,https://metaspace2020.eu/dataset/2024-05-23_14...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
29,2024-04-10_17h06m19s,8223301,metaspace,None,https://metaspace2020.eu/dataset/2024-04-10_17...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
30,2024-02-20_01h55m56s,d28-2014-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
31,2024-02-20_01h57m32s,d28-2017-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
32,2024-02-20_01h54m01s,d14-2295,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
33,2024-02-20_01h54m41s,d28-2006-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
34,2024-02-20_01h53m31s,d14-2015,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
35,2024-02-20_01h49m35s,d14-2001-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
36,2024-02-20_01h48m46s,d7-2024-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
37,2024-02-20_01h46m58s,d7-2020-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
38,2024-02-20_01h46m10s,d7-2004-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
39,2024-02-20_01h45m20s,d3-2023-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
40,2024-02-20_01h44m07s,d3-2012-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
41,2024-02-20_01h43m24s,d3-2010-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
42,2024-02-20_01h42m42s,d3-1807,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
43,2024-02-20_01h41m56s,d2-2053-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
44,2024-02-20_01h40m11s,d2-2042-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
45,2024-02-20_01h38m59s,d2-2018-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
46,2024-02-19_05h43m55s,d1-2016-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
47,2024-02-19_05h42m55s,d1-2005-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
48,2024-02-19_05h36m42s,d1-1829,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
49,2024-02-19_05h21m14s,d1-1817,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
50,2024-02-19_05h12m47s,con2060-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
51,2024-02-19_05h02m33s,c2_mus_kidney,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
52,2024-02-19_04h23m32s,control_c1,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_04...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
53,2022-12-01_15h43m13s,Kidney NEDC_Att35_25-2DFP- TU Dortmund - 20221024,metaspace,None,https://metaspace2020.eu/dataset/2022-12-01_15...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
54,2022-03-02_09h36m24s,IR_plasma_fresh_kidney_neg_mz300-1000,metaspace,None,https://metaspace2020.eu/dataset/2022-03-02_09...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
55,2022-03-02_09h12m28s,IR_plasma_FFPE_kidney_neg_mz300-1000,metaspace,None,https://metaspace2020.eu/dataset/2022-03-02_09...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
56,2022-02-28_12h36m26s,IR_plasma_FFPE_kidney_neg_mz80-305,metaspace,None,https://metaspace2020.eu/dataset/2022-02-28_12...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
57,2022-02-28_11h15m58s,IR_plasma_fresh_kidney_neg_mz80-305,metaspace,None,https://metaspace2020.eu/dataset/2022-02-28_11...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
58,2019-03-19_17h21m15s,kidney_test_metabolites,metaspace,None,https://metaspace2020.eu/dataset/2019-03-19_17...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
59,2017-04-20_09h06m22s,May4_kidney_serial_S25,metaspace,None,https://metaspace2020.eu/dataset/2017-04-20_09...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False

Found 60 datasets

Here we can see that proposals that have sense are between

In [6]:
coverage = explorer.count_mz_range_coverage(
    lower_bounds=[100 * i for i in range(1, 5)],
    upper_bounds=[100 * i for i in range(7, 15)],
)

range_counts_matrix = coverage.pivot(
    index="lower_bound",
    columns="upper_bound",
    values="dataset_count",
)

# from 200 to 900 we obtain 30 datasets, it should be enough
range_counts_matrix

upper_bound  700.0   800.0   900.0   1000.0  1100.0  1200.0  1300.0  1400.0
lower_bound
100.0            15      14       5       3       3       3       0       0
200.0            40      39      30       8       8       3       0       0
300.0            42      41      32      10       8       3       0       0
400.0            50      49      40      18      16      11       8       6

In [7]:
# this one severs for individual filtering
matching = explorer.select_mz_range(
    min_mz=200,
    max_mz=900,
)
matching

,dataset_id,name,source,project_accession,project_url,organisms,organism_parts,condition,growth_conditions,diseases,...,unannotated_pixel_count,annotated_pixel_fraction,annotation_fdr,spatial_annotation_count,spatial_annotation_database_count,spatial_stats_status,molecule_count,unique_molecule_count,unique_molecules,excluded
0,2026-04-22_21h03m00s,kidney_test_metabolites_null_mz_shift_10_til_550,metaspace,None,https://metaspace2020.eu/dataset/2026-04-22_21...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
1,2025-07-06_22h07m04s,msi2024013_20240909_multiomicsii_nor 50-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_22...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
2,2025-07-06_16h31m32s,msi2024013_20240909_multiomicsii_nedc 50-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_16...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
3,2024-05-23_14h25m01s,K3 vs K6 neg -Jano,metaspace,None,https://metaspace2020.eu/dataset/2024-05-23_14...,Mouse,Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
4,2024-04-10_17h06m19s,8223301,metaspace,None,https://metaspace2020.eu/dataset/2024-04-10_17...,Mus musculus (mouse),Kidney,Wildtype,,,...,None,None,0.1,None,None,None,None,None,,False
5,2024-02-20_01h55m56s,d28-2014-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
6,2024-02-20_01h57m32s,d28-2017-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
7,2024-02-20_01h54m01s,d14-2295,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
8,2024-02-20_01h54m41s,d28-2006-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
9,2024-02-20_01h53m31s,d14-2015,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
10,2024-02-20_01h49m35s,d14-2001-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
11,2024-02-20_01h48m46s,d7-2024-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
12,2024-02-20_01h46m58s,d7-2020-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
13,2024-02-20_01h46m10s,d7-2004-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
14,2024-02-20_01h45m20s,d3-2023-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
15,2024-02-20_01h44m07s,d3-2012-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
16,2024-02-20_01h43m24s,d3-2010-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
17,2024-02-20_01h42m42s,d3-1807,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
18,2024-02-20_01h41m56s,d2-2053-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
19,2024-02-20_01h40m11s,d2-2042-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
20,2024-02-20_01h38m59s,d2-2018-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
21,2024-02-19_05h43m55s,d1-2016-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
22,2024-02-19_05h42m55s,d1-2005-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
23,2024-02-19_05h36m42s,d1-1829,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
24,2024-02-19_05h21m14s,d1-1817,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
25,2024-02-19_05h12m47s,con2060-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
26,2024-02-19_05h02m33s,c2_mus_kidney,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
27,2024-02-19_04h23m32s,control_c1,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_04...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False
28,2019-03-19_17h21m15s,kidney_test_metabolites,metaspace,None,https://metaspace2020.eu/dataset/2019-03-19_17...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,None,None,0.1,None,None,None,None,None,,False
29,2017-04-20_09h06m22s,May4_kidney_serial_S25,metaspace,None,https://metaspace2020.eu/dataset/2017-04-20_09...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,None,None,0.1,None,None,None,None,None,,False

In [8]:
filters = {
    # Biological and acquisition metadata
    "organism": "Mouse",
    "organism_part": "Kidney",
    "polarity": "Negative",
    "condition": "Wildtype",  # matched tolerantly; also groups "Wildtype", "wildtype", etc.
    "mz_min": 200,
    "mz_max": 900,

    # Annotation filters and molecular statistics
    "annotation_fdr": 0.1,
    "min_annotation_count": 1,
    "include_molecule_stats": True,
    "include_spatial_annotation_stats": True, # REMARK: it filters unique values based on `annotation_fdr`
}

results_kidney = explorer.filter(filters)

2026-08-12 13:15:52,072 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.metaspace:550 | METASPACE cache reduced discovery to 61 candidate datasets

METASPACE discovery:   0%|          | 0/3 [00:00<?, ?stage/s]

Current operation:   0%|          | 0/1 [00:00<?, ?operation/s]

2026-08-12 13:15:52,821 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.metaspace:221 | METASPACE spatial plan contains 30 datasets and 1255 annotation images
2026-08-12 13:16:30,587 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.metaspace:267 | METASPACE discovery accepted 30 datasets and rejected 8738 datasets
2026-08-12 13:16:30,589 | INFO     | msi_autoencoder_wrapper.dataset_management.exploration.dataset_explorer:123 | Explorer retained 30 records from source metaspace

In [13]:
display(results_kidney)
print(f"Accepted {len(results_kidney)} datasets")

,dataset_id,name,source,project_accession,project_url,organisms,organism_parts,condition,growth_conditions,diseases,...,unannotated_pixel_count,annotated_pixel_fraction,annotation_fdr,spatial_annotation_count,spatial_annotation_database_count,spatial_stats_status,molecule_count,unique_molecule_count,unique_molecules,excluded
0,2026-04-22_21h03m00s,kidney_test_metabolites_null_mz_shift_10_til_550,metaspace,None,https://metaspace2020.eu/dataset/2026-04-22_21...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,75,0.991254,0.1,7,1,complete,7,3,"C13H14O3S-H, C24H28O5-H, C24H30O5-H",False
1,2025-07-06_22h07m04s,msi2024013_20240909_multiomicsii_nor 50-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_22...,Mus musculus (mouse),Kidney,Wildtype,,,...,0,1.000000,0.1,118,3,complete,103,44,"C10H13N4O8P-H, C10H14N5O8P-H, C10H15N5O10P2-H,...",False
2,2025-07-06_16h31m32s,msi2024013_20240909_multiomicsii_nedc 50-1350,metaspace,None,https://metaspace2020.eu/dataset/2025-07-06_16...,Mus musculus (mouse),Kidney,Wildtype,,,...,86,0.998785,0.1,32,2,complete,23,13,"C21H41O6P-H, C24H47NO10S-H, C26H43NO6+Cl, C34H...",False
3,2024-05-23_14h25m01s,K3 vs K6 neg -Jano,metaspace,None,https://metaspace2020.eu/dataset/2024-05-23_14...,Mouse,Kidney,Wildtype,,,...,67,0.996666,0.1,485,4,complete,311,221,"C10H12N2O5-H, C10H12N4O5-H, C10H15NO2S-H, C10H...",False
4,2024-04-10_17h06m19s,8223301,metaspace,None,https://metaspace2020.eu/dataset/2024-04-10_17...,Mus musculus (mouse),Kidney,Wildtype,,,...,0,1.000000,0.1,216,3,complete,124,69,"C10H14N4O5-H, C10H15N3O5+Cl, C10H20O2-H, C11H2...",False
5,2024-02-20_01h55m56s,d28-2014-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,4,0.999444,0.1,10,3,complete,7,0,,False
6,2024-02-20_01h57m32s,d28-2017-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,6,0.999217,0.1,18,3,complete,14,6,"C44H81O7P-H, C45H79O12P-H, C46H83O12P-H, C49H8...",False
7,2024-02-20_01h54m01s,d14-2295,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,3,0.999403,0.1,14,4,complete,10,7,"C15H19NO9[M]-, C17H12O10S[M]-, C18H12O4[M]-, C...",False
8,2024-02-20_01h54m41s,d28-2006-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,17,4,complete,14,1,C49H93O12P[M]-,False
9,2024-02-20_01h53m31s,d14-2015,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,22,4,complete,14,6,"C10H7NO3-H, C14H20N2O3S-H, C43H78NO8P[M]-, C46...",False
10,2024-02-20_01h49m35s,d14-2001-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,5,0.999396,0.1,17,4,complete,11,1,C20H20O10[M]-,False
11,2024-02-20_01h48m46s,d7-2024-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,58,0.992562,0.1,11,4,complete,7,0,,False
12,2024-02-20_01h46m58s,d7-2020-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,15,4,complete,11,0,,False
13,2024-02-20_01h46m10s,d7-2004-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,2,0.999774,0.1,11,4,complete,8,1,C53H100NO8P-H,False
14,2024-02-20_01h45m20s,d3-2023-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,15,0.998636,0.1,14,4,complete,9,0,,False
15,2024-02-20_01h44m07s,d3-2012-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,68,0.993780,0.1,14,4,complete,9,0,,False
16,2024-02-20_01h43m24s,d3-2010-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,15,4,complete,9,2,"C18H35IO2[M]-, C40H70NO8P[M]-",False
17,2024-02-20_01h42m42s,d3-1807,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,13,4,complete,10,4,"C10H20O7P2[M]-, C47H93O12P[M]-, C48H93NO13-H, ...",False
18,2024-02-20_01h41m56s,d2-2053-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,88,0.992736,0.1,7,3,complete,6,1,C14H30N2O4+Cl,False
19,2024-02-20_01h40m11s,d2-2042-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,81,0.992238,0.1,8,3,complete,7,0,,False
20,2024-02-20_01h38m59s,d2-2018-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-20_01...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,28,0.997557,0.1,8,4,complete,7,0,,False
21,2024-02-19_05h43m55s,d1-2016-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,1,0.999891,0.1,12,4,complete,10,1,C40H79O8P[M]-,False
22,2024-02-19_05h42m55s,d1-2005-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,4,0.999636,0.1,8,4,complete,6,2,"C26H46NO7P-H, C57H86O4[M]-",False
23,2024-02-19_05h36m42s,d1-1829,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,20,4,complete,15,6,"C42H81O7P[M]-, C47H83O10P-H, C47H88NO8P-H, C49...",False
24,2024-02-19_05h21m14s,d1-1817,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,16,4,complete,13,3,"C44H79O7P[M]-, C46H79O8P[M]-, C46H80NO7P-H",False
25,2024-02-19_05h12m47s,con2060-2,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,0,1.000000,0.1,14,4,complete,9,0,,False
26,2024-02-19_05h02m33s,c2_mus_kidney,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_05...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,64,0.992096,0.1,6,3,complete,5,1,C18H30O3S[M]-,False
27,2024-02-19_04h23m32s,control_c1,metaspace,None,https://metaspace2020.eu/dataset/2024-02-19_04...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,2,0.999734,0.1,18,4,complete,14,8,"C18H20N2O5+Cl, C43H77NO9-H, C47H91O12P[M]-, C5...",False
28,2019-03-19_17h21m15s,kidney_test_metabolites,metaspace,None,https://metaspace2020.eu/dataset/2019-03-19_17...,Mus musculus (mouse),Kidney,Wildtype,Caged,,...,123,0.985656,0.1,16,1,complete,16,6,"C10H16N2O7-H, C10H17N3O6S-H, C17H30O13-H, C22H...",False
29,2017-04-20_09h06m22s,May4_kidney_serial_S25,metaspace,None,https://metaspace2020.eu/dataset/2017-04-20_09...,Mus musculus (mouse),Kidney,Wildtype,N/A,,...,2082,0.804065,0.1,73,2,complete,53,28,"C10H19O6P-H, C12H22O8-H, C13H18N4O6-H, C15H14N...",False

Accepted 30 datasets

In [10]:
## to gigabyte transfer 
results_kidney['total_size_bytes'].sum() / 10**(9)

np.float64(30.238378985)

## 4. Export filters

In [14]:
output_path = Path(
    "data/kidney_workspace/configs/datasets/kidney.json"
)

exported = explorer.export_selection(
    output_path,
    sort_by="download_size_bytes",
    ascending = False
)

exported

2026-08-12 13:18:20,888 | INFO     | msi_autoencoder_wrapper.dataset_management.exploration.dataset_explorer:269 | Exported dataset query configuration to data/kidney_workspace/configs/datasets/kidney.json/filter.json

{'filters': PosixPath('data/kidney_workspace/configs/datasets/kidney.json/filter.json'),
 'selection': PosixPath('data/kidney_workspace/configs/datasets/kidney.json/selection.json')}