# Dataset management 01: Explore annotated mouse-bladder MSI data in PRIDE

This notebook searches metadata only. It displays accepted image pairs, remote sizes, annotation compatibility, rejected records, and PRIDE links before MSI data are downloaded. The exported JSON is consumed by the `msi-datasets query --filters` command.

In [ ]:
from pathlib import Path

from msi_dataset_manager.exploration import DatasetExplorer

explorer = DatasetExplorer(source="pride")

## Inspect and configure filters

The source reports supported fields and their meaning. The configuration requires unambiguous organism and organ metadata, a complete imzML/ibd pair, a supported curated molecule-to-pixel table, and downloadable checksums.

In [2]:
explorer.available_filters()

{'keyword': {'type': 'string', 'default': 'imzML'},
 'filter': {'type': 'string', 'description': 'Raw PRIDE API filter.'},
 'organisms': {'type': 'list[string]', 'api_field': 'organisms'},
 'organism_parts': {'type': 'list[string]', 'api_field': 'organismsPart'},
 'diseases': {'type': 'list[string]', 'api_field': 'diseases'},
 'instruments': {'type': 'list[string]', 'api_field': 'instruments'},
 'experiment_types': {'type': 'list[string]', 'api_field': 'experimentTypes'},
 'submission_types': {'type': 'list[string]', 'api_field': 'submissionType'},
 'publication_date_from': {'type': 'YYYY-MM-DD | null'},
 'publication_date_to': {'type': 'YYYY-MM-DD | null'},
 'required_metadata_fields': {'type': 'list[string]'},
 'single_value_metadata_fields': {'type': 'list[string]'},
 'max_pair_size_bytes': {'type': 'integer | null'},
 'exclude_dataset_ids': {'type': 'list[string]'},
 'require_annotation_source': {'type': 'boolean', 'required': True},
 'require_checksum': {'type': 'boolean', 'required': True},
 'page_size': {'type': 'positive integer', 'default': 100},
 'max_projects': {'type': 'positive integer', 'default': 500}}

In [20]:
filters = {
    "keyword": "imzML",
    # "organisms": ["Mus musculus (mouse)"],
    # "organism_parts": ["Urinary bladder", "Bladder"],
    # "experiment_types": ["mass spectrometry imaging"],
    # "required_metadata_fields": ["organisms", "organismParts"],
    # "single_value_metadata_fields": ["organisms", "organismParts", "diseases"],
    # "require_annotation_source": True,
    # "require_checksum": True,
    # "page_size": 100,
    # "max_projects": 500,
    # "exclude_dataset_ids": [],
}
explorer.set_filters(filters)

{'keyword': 'imzML'}

## Search and review

Accepted rows are independent MSI image pairs. `total_size_bytes` is the imzML plus ibd size reported before download. Open `project_url` to inspect the source. Rejected rows explain missing metadata, incomplete pairs, unavailable checksums, or unsupported annotations.

In [21]:
accepted = explorer.search()
accepted

2026-07-28 22:27:47,794 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD070149

Connected to the streaming API. Fetching data...
Successfully retrieved 207 items.
2026-07-28 22:27:49,347 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB929_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,348 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB929_cancer_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,348 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB929_normal_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,349 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB929_normal_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,349 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB931_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,350 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB931_cancer_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,351 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB931_normal_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,352 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB934_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,352 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB934_normal_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,353 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB941_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,354 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB941_normal_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,354 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB941_normal_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,355 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB943_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,355 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB943_cancer_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,356 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB943_normal_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,356 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB947_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,357 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB947_normal_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,357 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB950_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,358 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB950_normal_20um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,359 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB952_cancer_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)
2026-07-28 22:27:49,360 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD070149: unsupported annotation format for image 'PWB952_normal_10um_recal_M2' (https://www.ebi.ac.uk/pride/archive/projects/PXD070149)

2026-07-28 22:27:49,759 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD059505

Connected to the streaming API. Fetching data...
Successfully retrieved 13 items.
2026-07-28 22:27:50,196 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD059505: unsupported annotation format for image 'Mouse_brain_tryptic_digest_10um_Fig4F' (https://www.ebi.ac.uk/pride/archive/projects/PXD059505)
2026-07-28 22:27:50,197 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD059505: unsupported annotation format for image 'Mouse_brain_tryptic_digest_10um_Fig4L' (https://www.ebi.ac.uk/pride/archive/projects/PXD059505)
2026-07-28 22:27:50,198 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD059505: unsupported annotation format for image 'Mouse_brain_tryptic_digest_10um_Fig4M' (https://www.ebi.ac.uk/pride/archive/projects/PXD059505)
2026-07-28 22:27:50,199 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD059505: unsupported annotation format for image 'Mouse_brain_tryptic_digest_10um_FigS7B' (https://www.ebi.ac.uk/pride/archive/projects/PXD059505)

2026-07-28 22:27:50,766 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD053247

Connected to the streaming API. Fetching data...
Successfully retrieved 419 items.
2026-07-28 22:27:53,572 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_07_11_MB-TV_292061_s11' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,573 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_07_19_MB-TV_1-10_s06_img' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,574 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_08_24_MB-hSOD1wt-B1_s03' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,575 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_09_27_L1-27' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,575 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_10_25_cerebimg2_30x50_33L' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,576 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_10_31_MB-292061_s09_hires_30x50' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,577 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2022_11_01_MB_hWT_st02_hires_HPF' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,577 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2023_06_21_MSC_327570_94x100_fix' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,578 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2023_06_21_MSC_327571_94x100_fix' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,579 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2023_07_11_MB-hSOD-327571_10ums_200x200' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,580 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2023_10_02_MSC-348484L_94x100' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,581 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2023_10_03_MSC-348486_94x100_s09' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)
2026-07-28 22:27:53,582 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD053247: unsupported annotation format for image '2023_10_09_MSC-348486_s06_28x30_23Lfix' (https://www.ebi.ac.uk/pride/archive/projects/PXD053247)

2026-07-28 22:27:54,082 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD049325

Connected to the streaming API. Fetching data...
Successfully retrieved 66 items.
2026-07-28 22:27:54,948 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S15_210716_pa_ucl_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,948 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S15_210716_pa_ucl_s15_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,949 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S15_210716_pa_ucl_sad1_lip' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,951 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S15_210716_pa_ucl_sad1_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,951 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S16_20210819_pa_ucl_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,952 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S16_20210819_pa_ucl_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,953 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S1_pa_p7403_lip-neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,954 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S1_pa_p7403_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,955 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S1_sad_p4719_lip-neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,956 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S1_sad_p4719_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,957 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S2_20201105_pa_ucl_s2_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,958 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S2_20201105_pa_ucl_s2_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,959 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S2_20201105_pa_ucl_s2_sad_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,960 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S2_20201105_pa_ucl_s2_sad_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,960 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S3_20201111_pa_ucl_s3_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,961 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S3_20201111_pa_ucl_s3_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,962 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S3_20201111_pa_ucl_s3_sad_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,963 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S3_20201111_pa_ucl_s3_sad_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,964 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S4_20201119_pa_ucl_s4_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,965 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S4_20201119_pa_ucl_s4_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,966 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S5_2001126_pa_ucl_s5_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,967 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S5_2001126_pa_ucl_s5_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,967 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S5_2001126_pa_ucl_s5_sad_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,968 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S5_2001126_pa_ucl_s5_sad_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,969 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S6_20201203_pa_ucl_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,970 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S6_20201203_pa_ucl_pa_p7311' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,970 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S6_20201203_pa_ucl_s6_sad_p1210' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,971 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S6_20201203_pa_ucl_sad_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,972 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S7_20210121_pa_ucl_pa_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,973 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S7_20210121_pa_ucl_pa_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,974 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S7_20210121_pa_ucl_sad_neg' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)
2026-07-28 22:27:54,975 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD049325: unsupported annotation format for image 'S7_20210121_pa_ucl_sad_pep' (https://www.ebi.ac.uk/pride/archive/projects/PXD049325)

2026-07-28 22:27:53,791 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD048809

Connected to the streaming API. Fetching data...
Successfully retrieved 17 items.
2026-07-28 22:27:54,427 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD048809: unsupported annotation format for image '20230130_rf1_msi2023001_slide001_ctrls'; tabular project files: Muscle_1_Pixel-info.csv, Muscle_2_Pixel-info.csv, Muscle_3_Pixel-info.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD048809)
2026-07-28 22:27:54,428 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD048809: unsupported annotation format for image '20230130_rf1_msi2023001_slide001_m1'; tabular project files: Muscle_1_Pixel-info.csv, Muscle_2_Pixel-info.csv, Muscle_3_Pixel-info.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD048809)
2026-07-28 22:27:54,429 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD048809: unsupported annotation format for image '20230130_rf1_msi2023001_slide001_m2'; tabular project files: Muscle_1_Pixel-info.csv, Muscle_2_Pixel-info.csv, Muscle_3_Pixel-info.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD048809)
2026-07-28 22:27:54,429 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD048809: unsupported annotation format for image '20230130_rf1_msi2023001_slide001_m3'; tabular project files: Muscle_1_Pixel-info.csv, Muscle_2_Pixel-info.csv, Muscle_3_Pixel-info.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD048809)

2026-07-28 22:27:54,869 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD047820

Connected to the streaming API. Fetching data...
Successfully retrieved 33 items.
2026-07-28 22:27:55,389 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample1' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,390 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample1_cal33_6_1_0_15' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,391 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample2' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,392 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample2_cal33_6_1_0_15' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,393 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample3' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,394 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample3_cal33_6_1_0_15' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,394 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample4' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,395 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample4_cal33_6_1_0_15' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,395 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample5' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)
2026-07-28 22:27:55,396 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD047820: unsupported annotation format for image 'Sample5_cal33_6_1_0_15' (https://www.ebi.ac.uk/pride/archive/projects/PXD047820)

2026-07-28 22:27:55,898 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD045377

Connected to the streaming API. Fetching data...
Successfully retrieved 60 items.
2026-07-28 22:27:56,613 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoA1cristalA1' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,614 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoA1cristalA4_v2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,614 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoA2cristalA1' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,615 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'TejidoA2cristalA2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,615 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoA2cristalA4_v2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,616 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoAcristalB3' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,617 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoAcristalB4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,619 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoBcristalA1' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,620 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'TejidoBcristalA2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,621 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoBcristalA4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,622 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoBcristalB3' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,623 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoBcristalB4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,624 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoC1cristalB4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,625 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoC2cristalB3' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,626 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoC2cristalB4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,627 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'TejidoCcristalA2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,629 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoCcristalA4_v2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,630 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoD1cristalA1' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,632 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'TejidoD1cristalA2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,633 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoD1cristalA4_v2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,633 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoD2cristalA1' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,634 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'TejidoD2cristalA2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,635 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoD2cristalA4_v2' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,636 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoD3cristalA4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,637 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoDcristalB3' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)
2026-07-28 22:27:56,638 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD045377: unsupported annotation format for image 'tejidoDcristalB4' (https://www.ebi.ac.uk/pride/archive/projects/PXD045377)

2026-07-28 22:27:57,182 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD039398

Connected to the streaming API. Fetching data...
Successfully retrieved 100 items.

2026-07-28 22:27:58,689 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD038114

Connected to the streaming API. Fetching data...
Successfully retrieved 103 items.
2026-07-28 22:27:59,705 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '1.5.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,706 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '14.9'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,706 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '15.10'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,707 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '16.15.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,708 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '16.15.2'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,708 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '17.2'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,709 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '3.6.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,710 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '3.6.2'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,711 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '4.8.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,711 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '4.8.2'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,712 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '5.10.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,714 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '6.14.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,714 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image '6.14.2'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,715 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image 'M1.3'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,716 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image 'M13.6'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,716 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image 'M7.8'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,717 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image 'M8.20.1'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)
2026-07-28 22:27:59,718 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD038114: unsupported annotation format for image 'M8.20.2'; tabular project files: AllQuantifiedPeaks.tsv, AllQuantifiedPeptides.tsv, AllQuantifiedProteinGroups.tsv, RA1-calib_ProteinGroups.tsv, RA14-calib_ProteinGroups.tsv, RA15-calib_ProteinGroups.tsv, RA16-calib_ProteinGroups.tsv, RA17-calib_ProteinGroups.tsv, RA3-calib_ProteinGroups.tsv, RA4-calib_ProteinGroups.tsv, RA5-calib_ProteinGroups.tsv, RA6-calib_ProteinGroups.tsv, RAM1-calib_ProteinGroups.tsv, RAM13-calib_ProteinGroups.tsv, RAM7-calib_ProteinGroups.tsv, RAM8-calib_ProteinGroups.tsv, RA_Blank_2-calib_ProteinGroups.tsv, RA_Blank_ProteinGroups.tsv (https://www.ebi.ac.uk/pride/archive/projects/PXD038114)

2026-07-28 22:28:00,199 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD028949

Connected to the streaming API. Fetching data...
Successfully retrieved 60 items.

2026-07-28 22:28:01,336 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD026459

Connected to the streaming API. Fetching data...
Successfully retrieved 18 items.
2026-07-28 22:28:01,794 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD026459: unsupported annotation format for image 'TMA1' (https://www.ebi.ac.uk/pride/archive/projects/PXD026459)
2026-07-28 22:28:01,794 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD026459: unsupported annotation format for image 'TMA2' (https://www.ebi.ac.uk/pride/archive/projects/PXD026459)

2026-07-28 22:28:02,171 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD025826

Connected to the streaming API. Fetching data...
Successfully retrieved 11 items.
2026-07-28 22:28:02,629 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025826: unsupported annotation format for image '20180425_glioma' (https://www.ebi.ac.uk/pride/archive/projects/PXD025826)
2026-07-28 22:28:02,630 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025826: unsupported annotation format for image '20180510_VH153520A' (https://www.ebi.ac.uk/pride/archive/projects/PXD025826)
2026-07-28 22:28:02,631 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025826: unsupported annotation format for image '20180516_MR0703A' (https://www.ebi.ac.uk/pride/archive/projects/PXD025826)
2026-07-28 22:28:02,631 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025826: unsupported annotation format for image '20180516VH140622' (https://www.ebi.ac.uk/pride/archive/projects/PXD025826)
2026-07-28 22:28:02,632 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025826: unsupported annotation format for image 'VH151139A' (https://www.ebi.ac.uk/pride/archive/projects/PXD025826)

2026-07-28 22:28:03,058 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD025594

Connected to the streaming API. Fetching data...
Successfully retrieved 31 items.
2026-07-28 22:28:03,619 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'B5-lnm_negative_core_id_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,620 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'B5-lnm_positive_core_id_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,620 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'B5-not_tested-core_id_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,621 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'D5-lnm_negative_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,621 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'D5-lnm_positive_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,622 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'D5-not_tested-unknown_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,623 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'E5-lnm_negative_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,624 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'E5-lnm_positive_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)
2026-07-28 22:28:03,625 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025594: unsupported annotation format for image 'E5-unknown_-_no_normalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD025594)

2026-07-28 22:28:04,144 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD025486

Connected to the streaming API. Fetching data...
Successfully retrieved 92 items.
2026-07-28 22:28:04,954 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025486: unsupported annotation format for image 'Bovin_lens'; tabular project files: FDR.CSV, PROTEIN_FDR.CSV, Peptide_1st_ID.csv, Peptide_1st_ID_score_rank_SQRTP.csv, Peptide_2nd_ID_score_rankSQRTP_Rank_above_3.csv, Peptide_region_file.csv, Peptide_segment_PMF_RESULT_1.csv, Peptide_segment_PMF_RESULT_2.csv, Peptide_segment_PMF_RESULT_3.csv, Peptide_segment_PMF_RESULT_4.csv, Peptide_segment_PMF_RESULT_Cerebrum.csv, Peptide_segment_PMF_RESULT_Cortex.csv, Peptide_segment_PMF_RESULT_Cranial_nerves.csv, Peptide_segment_PMF_RESULT_Fiber_tracts.csv, Peptide_segment_PMF_RESULT_Medial_septal_Nucleus.csv, Peptide_segment_PMF_RESULT_Optic_chiasm.csv, Peptide_segment_PMF_RESULT_TBD.csv, Protein_ID_score_rank_SQRTP.csv, Protein_segment_PMF_RESULT_1.csv, Protein_segment_PMF_RESULT_2.csv, Protein_segment_PMF_RESULT_3.csv, Protein_segment_PMF_RESULT_4.csv, Protein_segment_PMF_RESULT_Cerebrum.csv, Protein_segment_PMF_RESULT_Cortex.csv, Protein_segment_PMF_RESULT_Cranial_nerves.csv, Protein_segment_PMF_RESULT_Fiber_tracts.csv, Protein_segment_PMF_RESULT_Medial_septal_Nucleus.csv, Protein_segment_PMF_RESULT_Optic_chiasm.csv, Protein_segment_PMF_RESULT_TBD.csv, Spectrum.csv, spatialKMeans_RESULT_centers.csv, spatialKMeans_RESULT_centers_4_segs.csv, spatialKMeans_RESULT_cluster.csv, spatialKMeans_RESULT_cluster_4_segs.csv, spatialKMeans_RESULT_withinss.csv, spatialKMeans_RESULT_withinss_4_segs.csv, spatialKMeans__RESULT_centers_200_segs.csv, spatialKMeans__RESULT_centers_4_segs.csv, spatialKMeans__RESULT_cluster_200_segs.csv, spatialKMeans__RESULT_cluster_4_segs.csv, spatialKMeans__RESULT_correlation_200_segs.csv, spatialKMeans__RESULT_correlation_4_segs.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD025486)
2026-07-28 22:28:04,954 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD025486: unsupported annotation format for image 'Mouse_brain'; tabular project files: FDR.CSV, PROTEIN_FDR.CSV, Peptide_1st_ID.csv, Peptide_1st_ID_score_rank_SQRTP.csv, Peptide_2nd_ID_score_rankSQRTP_Rank_above_3.csv, Peptide_region_file.csv, Peptide_segment_PMF_RESULT_1.csv, Peptide_segment_PMF_RESULT_2.csv, Peptide_segment_PMF_RESULT_3.csv, Peptide_segment_PMF_RESULT_4.csv, Peptide_segment_PMF_RESULT_Cerebrum.csv, Peptide_segment_PMF_RESULT_Cortex.csv, Peptide_segment_PMF_RESULT_Cranial_nerves.csv, Peptide_segment_PMF_RESULT_Fiber_tracts.csv, Peptide_segment_PMF_RESULT_Medial_septal_Nucleus.csv, Peptide_segment_PMF_RESULT_Optic_chiasm.csv, Peptide_segment_PMF_RESULT_TBD.csv, Protein_ID_score_rank_SQRTP.csv, Protein_segment_PMF_RESULT_1.csv, Protein_segment_PMF_RESULT_2.csv, Protein_segment_PMF_RESULT_3.csv, Protein_segment_PMF_RESULT_4.csv, Protein_segment_PMF_RESULT_Cerebrum.csv, Protein_segment_PMF_RESULT_Cortex.csv, Protein_segment_PMF_RESULT_Cranial_nerves.csv, Protein_segment_PMF_RESULT_Fiber_tracts.csv, Protein_segment_PMF_RESULT_Medial_septal_Nucleus.csv, Protein_segment_PMF_RESULT_Optic_chiasm.csv, Protein_segment_PMF_RESULT_TBD.csv, Spectrum.csv, spatialKMeans_RESULT_centers.csv, spatialKMeans_RESULT_centers_4_segs.csv, spatialKMeans_RESULT_cluster.csv, spatialKMeans_RESULT_cluster_4_segs.csv, spatialKMeans_RESULT_withinss.csv, spatialKMeans_RESULT_withinss_4_segs.csv, spatialKMeans__RESULT_centers_200_segs.csv, spatialKMeans__RESULT_centers_4_segs.csv, spatialKMeans__RESULT_cluster_200_segs.csv, spatialKMeans__RESULT_cluster_4_segs.csv, spatialKMeans__RESULT_correlation_200_segs.csv, spatialKMeans__RESULT_correlation_4_segs.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD025486)

2026-07-28 22:28:05,417 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD021275

Connected to the streaming API. Fetching data...
Successfully retrieved 44 items.
2026-07-28 22:28:06,090 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'a2'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,091 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'b1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,092 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'd1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,092 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'e2'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,093 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'f2'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,094 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'g2'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,095 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'h1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,096 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'i2'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,097 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'j2'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,098 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'k1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,099 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'l1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,100 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'm1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,101 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'n1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,102 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: incomplete or ambiguous imzML/ibd pair 'o1' (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)
2026-07-28 22:28:06,103 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD021275: unsupported annotation format for image 'p1'; tabular project files: A2.csv, B1.csv, D1.csv, E2.csv, F2.csv, G2.csv, H1.csv, I2.csv, J2.csv, K1.csv, L1.csv, M1.csv, N1.csv, O1.csv, P1.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD021275)

2026-07-28 22:28:06,511 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD020824

Connected to the streaming API. Fetching data...
Successfully retrieved 16 items.
2026-07-28 22:28:07,007 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD020824: unsupported annotation format for image 'APPNL-G-F_18weeks_LP2-10kDa_20um' (https://www.ebi.ac.uk/pride/archive/projects/PXD020824)
2026-07-28 22:28:07,008 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD020824: unsupported annotation format for image 'APPNL-G-F_67weeks_LP2-10kDa_20um' (https://www.ebi.ac.uk/pride/archive/projects/PXD020824)
2026-07-28 22:28:07,009 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD020824: unsupported annotation format for image 'APPNL_66weeks_LP2-10kDa_20um' (https://www.ebi.ac.uk/pride/archive/projects/PXD020824)
2026-07-28 22:28:07,009 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD020824: unsupported annotation format for image 'APPPS1_20weeks_LP2-10kDa_20um' (https://www.ebi.ac.uk/pride/archive/projects/PXD020824)
2026-07-28 22:28:07,010 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD020824: unsupported annotation format for image 'C57BL6JatRJ_69weeks_LP2-10kDa_20um' (https://www.ebi.ac.uk/pride/archive/projects/PXD020824)

2026-07-28 22:28:07,460 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD011104

Connected to the streaming API. Fetching data...
Successfully retrieved 34 items.
2026-07-28 22:28:08,052 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'agingexperiment' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,053 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'GastricMouseTumorMALDIFT-ICR' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,054 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'kidney-inhibconccurve' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,055 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'liver-inhibconccurve' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,056 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'mousestomachmaldi-tof' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,057 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'muscle-inhibconccurve' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,058 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'pancreas-inhibconccurve' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,058 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'selectivitygastricmousestomachmaldi-tof' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,059 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'spleen-inhibconccurve' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,060 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'tcea-wash' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)
2026-07-28 22:28:08,061 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011104: unsupported annotation format for image 'time-curve-dataset' (https://www.ebi.ac.uk/pride/archive/projects/PXD011104)

2026-07-28 22:28:08,484 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD019666

Connected to the streaming API. Fetching data...
Successfully retrieved 21 items.
2026-07-28 22:28:08,973 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets-1c-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)
2026-07-28 22:28:08,974 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets-1d-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)
2026-07-28 22:28:08,974 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets1a-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)
2026-07-28 22:28:08,975 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets2a-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)
2026-07-28 22:28:08,975 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets2b-01-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)
2026-07-28 22:28:08,976 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets2b-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)
2026-07-28 22:28:08,977 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019666: unsupported annotation format for image 'mets2d-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019666)

2026-07-28 22:28:09,472 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD019662

Connected to the streaming API. Fetching data...
Successfully retrieved 50 items.
2026-07-28 22:28:10,150 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5A-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,151 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5A-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,151 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5B-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,152 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5B-alltumours-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,153 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5C-all-normal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,154 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5C-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,155 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5D-combined-normal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,156 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5D-combined-tumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,157 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5E-combinednormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,158 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5E-combinedtumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,159 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5F-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,159 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA5F-alltumours-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,160 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7A-all-normal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,160 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7A-all-tumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,161 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7B-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,161 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7B-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,162 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7C-all-normal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,163 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7C-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,163 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7D-combinednormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)
2026-07-28 22:28:10,165 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019662: unsupported annotation format for image 'TMA7D-combinedtumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019662)

2026-07-28 22:28:10,595 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD019653

Connected to the streaming API. Fetching data...
Successfully retrieved 25 items.
2026-07-28 22:28:11,102 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6A-all-normal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,103 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6A-all-tumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,104 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6B-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,105 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6B-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,106 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6D-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,107 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6D-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,108 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6E-all-normal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,109 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6E-all-tumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,110 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6F-allnormal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)
2026-07-28 22:28:11,111 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019653: unsupported annotation format for image 'TMA6F-alltumour-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD019653)

2026-07-28 22:28:11,509 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD019255

Connected to the streaming API. Fetching data...
Successfully retrieved 15 items.
2026-07-28 22:28:11,925 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019255: unsupported annotation format for image 'pymt-rock-kd-regions-nonormalization-01' (https://www.ebi.ac.uk/pride/archive/projects/PXD019255)
2026-07-28 22:28:11,926 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD019255: unsupported annotation format for image 'pymt-rock-kd-regions-nonormalization-02' (https://www.ebi.ac.uk/pride/archive/projects/PXD019255)

2026-07-28 22:28:12,338 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD014310

Connected to the streaming API. Fetching data...
Successfully retrieved 13 items.
2026-07-28 22:28:12,848 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD014310: unsupported annotation format for image 'n-glycan_homo_vs_hetero' (https://www.ebi.ac.uk/pride/archive/projects/PXD014310)
2026-07-28 22:28:12,848 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD014310: unsupported annotation format for image 'n-glycan_homo_vs_hetero_2' (https://www.ebi.ac.uk/pride/archive/projects/PXD014310)
2026-07-28 22:28:12,849 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD014310: unsupported annotation format for image 'trypticpeptide_after' (https://www.ebi.ac.uk/pride/archive/projects/PXD014310)
2026-07-28 22:28:12,849 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD014310: unsupported annotation format for image 'trypticpeptide_before' (https://www.ebi.ac.uk/pride/archive/projects/PXD014310)

2026-07-28 22:28:13,276 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD016146

Connected to the streaming API. Fetching data...
Successfully retrieved 5 items.
2026-07-28 22:28:13,662 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD016146: unsupported annotation format for image '5mixes_onratliver_50micron' (https://www.ebi.ac.uk/pride/archive/projects/PXD016146)

2026-07-28 22:28:14,165 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD013397

Connected to the streaming API. Fetching data...
Successfully retrieved 31 items.
2026-07-28 22:28:14,694 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150722_Cancer_08P5640_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,695 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150723_BenignLHS_08P5640_RHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,696 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150723_Cancer_08P5640_RHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,697 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150724_HCCA_BenignLHS_08P7070_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,697 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150724_HCCA_BenignRHS_08P7070_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,698 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150724_HCCA_Cancer_08P7070_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,699 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150727_Benign_08P3105-RHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,700 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150727_Benign_08P3105_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,701 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150727_Cancer_08P3105_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,701 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150728_Benign_08P2031_RHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,702 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150728_Cancer_08P2031_RHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,703 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150730_Benign_08P9220_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,704 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150730_Cancer_08P9220_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,705 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150805_Benign_08P15660_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,706 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150805_Cancer_08P15660_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,707 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150806_Benign_08P9361_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,708 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair '150806_Cancer_08P9361_LHS' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,711 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair 'LHSsectn2_Benign2Adjacent_OBP5627' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)
2026-07-28 22:28:14,712 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD013397: incomplete or ambiguous imzML/ibd pair 'LHSsectn_Cancer_OBP5627' (https://www.ebi.ac.uk/pride/archive/projects/PXD013397)

2026-07-28 22:28:15,252 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD011262

Connected to the streaming API. Fetching data...
Successfully retrieved 103 items.
2026-07-28 22:28:16,287 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_C3_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,288 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_C3_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,289 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_C3_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,290 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_L3_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,291 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_L5_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,293 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_L6_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,294 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_R2_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,294 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_R3_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,295 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '10Day_R3_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,297 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_C1_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,298 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1day_C4_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,299 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_C9_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,299 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_L21_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,300 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_L5_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,301 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_L7_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,302 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_R21_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,303 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1Day_R2_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,304 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '1day_R3_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,305 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_C1_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,306 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_C3_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,307 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_C7_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,307 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_L5_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,309 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_L6_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,311 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_L7_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,312 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_R2_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,314 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_R2_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,315 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '3Day_R2_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,317 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_C11_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,317 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_C3_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,318 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_C6_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,319 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_L21_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,320 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_L6_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,321 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_L7_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,322 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_R21_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,323 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_R2_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,324 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image '7Day_R3_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,325 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_10_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,326 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_10_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,326 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_12-9_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,327 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_15_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,328 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_17_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,329 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_17_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,330 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_4_n1' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,331 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_4_n2' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)
2026-07-28 22:28:16,333 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD011262: unsupported annotation format for image 'Sham_6_n3' (https://www.ebi.ac.uk/pride/archive/projects/PXD011262)

2026-07-28 22:28:16,778 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD010990

Connected to the streaming API. Fetching data...
Successfully retrieved 20 items.
2026-07-28 22:28:17,243 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds1' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,244 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds18' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,245 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds19' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,246 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds2' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,247 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds20' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,247 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds24' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,248 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds26' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,249 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds3' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)
2026-07-28 22:28:17,252 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD010990: unsupported annotation format for image 'Ds4' (https://www.ebi.ac.uk/pride/archive/projects/PXD010990)

2026-07-28 22:28:17,703 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD009808

Connected to the streaming API. Fetching data...
Successfully retrieved 10 items.
2026-07-28 22:28:18,203 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD009808: unsupported annotation format for image 'cal-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD009808)
2026-07-28 22:28:18,204 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD009808: unsupported annotation format for image 'control-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD009808)
2026-07-28 22:28:18,205 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD009808: unsupported annotation format for image 'png1-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD009808)
2026-07-28 22:28:18,205 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD009808: unsupported annotation format for image 'png2-nonormalization' (https://www.ebi.ac.uk/pride/archive/projects/PXD009808)

2026-07-28 22:28:18,597 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD003172

Connected to the streaming API. Fetching data...
Successfully retrieved 3 items.
2026-07-28 22:28:18,977 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD003172: unsupported annotation format for image 'T019_Recall716.12461' (https://www.ebi.ac.uk/pride/archive/projects/PXD003172)

2026-07-28 22:28:19,358 - INFO - Fetching checksum file from https://www.ebi.ac.uk/pride/ws/archive/v3/files/checksum/PXD001283

Connected to the streaming API. Fetching data...
Successfully retrieved 4 items.
2026-07-28 22:28:19,733 | WARNING  | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:617 | Rejected PRIDE record PXD001283: unsupported annotation format for image 'HR2MSImouseurinarybladderS096'; tabular project files: HR2MSImouseurinarybladderS096-results.csv (https://www.ebi.ac.uk/pride/archive/projects/PXD001283)
2026-07-28 22:28:19,734 | INFO     | msi_autoencoder_wrapper.dataset_management.sources.strategies.pride:190 | PRIDE discovery accepted 0 image pairs and rejected 300 records
2026-07-28 22:28:19,734 | INFO     | msi_autoencoder_wrapper.dataset_management.exploration.dataset_explorer:100 | Explorer retained 0 records from source pride

Empty DataFrame
Columns: [dataset_id, name, source, project_accession, project_url, organisms, organism_parts, diseases, instruments, total_size_bytes, download_size_bytes, annotation_status, excluded]
Index: []

In [22]:
rejected = explorer.rejected()
rejected

,project_accession,dataset_id,reason,project_url
0,PXD070149,None,unsupported annotation format for image 'PWB92...,https://www.ebi.ac.uk/pride/archive/projects/P...
1,PXD070149,None,unsupported annotation format for image 'PWB92...,https://www.ebi.ac.uk/pride/archive/projects/P...
2,PXD070149,None,unsupported annotation format for image 'PWB92...,https://www.ebi.ac.uk/pride/archive/projects/P...
3,PXD070149,None,unsupported annotation format for image 'PWB92...,https://www.ebi.ac.uk/pride/archive/projects/P...
4,PXD070149,None,unsupported annotation format for image 'PWB93...,https://www.ebi.ac.uk/pride/archive/projects/P...
...,...,...,...,...
295,PXD009808,None,unsupported annotation format for image 'contr...,https://www.ebi.ac.uk/pride/archive/projects/P...
296,PXD009808,None,unsupported annotation format for image 'png1-...,https://www.ebi.ac.uk/pride/archive/projects/P...
297,PXD009808,None,unsupported annotation format for image 'png2-...,https://www.ebi.ac.uk/pride/archive/projects/P...
298,PXD003172,None,unsupported annotation format for image 'T019_...,https://www.ebi.ac.uk/pride/archive/projects/P...
299,PXD001283,None,unsupported annotation format for image 'HR2MS...,https://www.ebi.ac.uk/pride/archive/projects/P...

## Exclude reviewed images

After opening project links, place unwanted `dataset_id` values below. Exclusions become part of the exported query configuration.

In [ ]:
excluded_dataset_ids = []
if excluded_dataset_ids:
    explorer.exclude(excluded_dataset_ids)
explorer.results()

In [ ]:
output_path = Path("workspace/configs/datasets/pride-mouse-bladder/filter.json")
explorer.export_config(output_path)

## Use the exported configuration

Run `msi-datasets query --source pride --workspace-path workspace --filters workspace/configs/datasets/pride-mouse-bladder/filter.json --selection workspace/configs/datasets/pride-mouse-bladder/selection.json`, review the selection, and then pass that selection to `download --source pride`. See [Use the msi-datasets CLI](../../how-to/dataset-management/command-line-workflow.md) for the complete command reference.